export const typeCustomerList = [
  { value: "tenant", label: "Concessionária" },
  { value: "customer", label: "Cliente" }
]

export const statusList = [
  { value: "Não Informado", label: "Não Informado" },
  { value: "Ativo", label: "Ativo" },
  { value: "Preparando", label: "preparando" },
  { value: "Disponivel", label: "disponivel" },
  { value: "Repasse", label: "repasse" }
]

export const typeTerm = [
  { value: "venda", label: "venda" },
  { value: "compra", label: "compra" }
]

export const listOccupation = [
  { value: "Aposentado/Pencionista", label: "Aposentado/Pencionista" },
  { value: "Assalariado", label: "Assalariado" },
  { value: "Autônomo", label: "Autônomo" },
  { value: "Liberal", label: "Liberal" },
  { value: "Sócio/Empresário", label: "Sócio/Empresário" }
]

export const typesAddressList = [
  { value: "cliente", label: "Cliente" },
  { value: "vendedor", label: "Vendedor" }
]

export const listType = [
  { value: 'Carros', label: 'Carros' },
  { value: 'Motos', label: 'Motos' },
  { value: 'Caminhoes', label: 'Caminhões' },
  { value: 'Náutica', label: 'Náutica' }
]

export const listManufacturer = [
  { value: "CHEVROLET", label: "CHEVROLET" },
  { value: "VOLKSWAGEN", label: "VOLKSWAGEN" },
  { value: "FIAT", label: "FIAT" },
  { value: "MERCEDES-BENZ", label: "MERCEDES-BENZ" },
  { value: "CITROEN", label: "CITROEN" },
  { value: "CHANA", label: "CHANA" },
  { value: "HONDA", label: "HONDA" },
  { value: "SUBARU", label: "SUBARU" },
  { value: "FERRARI", label: "FERRARI" },
  { value: "BUGATTI", label: "BUGATTI" },
  { value: "LAMBORGHINI", label: "LAMBORGHINI" },
  { value: "FORD", label: "FORD" },
  { value: "HYUNDAI", label: "HYUNDAI" },
  { value: "JAC", label: "JAC" },
  { value: "KIA", label: "KIA" },
  { value: "GURGEL", label: "GURGEL" },
  { value: "DODGE", label: "DODGE" },
  { value: "CHRYSLER", label: "CHRYSLER" },
  { value: "BENTLEY", label: "BENTLEY" },
  { value: "SSANGYONG", label: "SSANGYONG" },
  { value: "PEUGEOT", label: "PEUGEOT" },
  { value: "TOYOTA", label: "TOYOTA" },
  { value: "RENAULT", label: "RENAULT" },
  { value: "ACURA", label: "ACURA" },
  { value: "ADAMO", label: "ADAMO" },
  { value: "AGRALE", label: "AGRALE" },
  { value: "ALFA ROMEO", label: "ALFA ROMEO" },
  { value: "AMERICAR", label: "AMERICAR" },
  { value: "ASTON MARTIN", label: "ASTON MARTIN" },
  { value: "AUDI", label: "AUDI" },
  { value: "BEACH", label: "BEACH" },
  { value: "BIANCO", label: "BIANCO" },
  { value: "BMW", label: "BMW" },
  { value: "BORGWARD", label: "BORGWARD" },
  { value: "BRILLIANCE", label: "BRILLIANCE" },
  { value: "BUICK", label: "BUICK" },
  { value: "CBT", label: "CBT" },
  { value: "NISSAN", label: "NISSAN" },
  { value: "CHAMONIX", label: "CHAMONIX" },
  { value: "CHEDA", label: "CHEDA" },
  { value: "CHERY", label: "CHERY" },
  { value: "CORD", label: "CORD" },
  { value: "COYOTE", label: "COYOTE" },
  { value: "CROSS LANDER", label: "CROSS LANDER" },
  { value: "DAEWOO", label: "DAEWOO" },
  { value: "DAIHATSU", label: "DAIHATSU" },
  { value: "VOLVO", label: "VOLVO" },
  { value: "DE SOTO", label: "DE SOTO" },
  { value: "DETOMAZO", label: "DETOMAZO" },
  { value: "DELOREAN", label: "DELOREAN" },
  { value: "DKW-VEMAG", label: "DKW-VEMAG" },
  { value: "SUZUKI", label: "SUZUKI" },
  { value: "EAGLE", label: "EAGLE" },
  { value: "EFFA", label: "EFFA" },
  { value: "ENGESA", label: "ENGESA" },
  { value: "ENVEMO", label: "ENVEMO" },
  { value: "FARUS", label: "FARUS" },
  { value: "FERCAR", label: "FERCAR" },
  { value: "FNM", label: "FNM" },
  { value: "PONTIAC", label: "PONTIAC" },
  { value: "PORSCHE", label: "PORSCHE" },
  { value: "GEO", label: "GEO" },
  { value: "GRANCAR", label: "GRANCAR" },
  { value: "GREAT WALL", label: "GREAT WALL" },
  { value: "HAFEI", label: "HAFEI" },
  { value: "HOFSTETTER", label: "HOFSTETTER" },
  { value: "HUDSON", label: "HUDSON" },
  { value: "HUMMER", label: "HUMMER" },
  { value: "INFINITI", label: "INFINITI" },
  { value: "INTERNATIONAL", label: "INTERNATIONAL" },
  { value: "JAGUAR", label: "JAGUAR" },
  { value: "JEEP", label: "JEEP" },
  { value: "JINBEI", label: "JINBEI" },
  { value: "JPX", label: "JPX" },
  { value: "KAISER", label: "KAISER" },
  { value: "KOENIGSEGG", label: "KOENIGSEGG" },
  { value: "LAUTOMOBILE", label: "LAUTOMOBILE" },
  { value: "LAUTOCRAFT", label: "LAUTOCRAFT" },
  { value: "LADA", label: "LADA" },
  { value: "LANCIA", label: "LANCIA" },
  { value: "LAND ROVER", label: "LAND ROVER" },
  { value: "LEXUS", label: "LEXUS" },
  { value: "LIFAN", label: "LIFAN" },
  { value: "LINCOLN", label: "LINCOLN" },
  { value: "LOBINI", label: "LOBINI" },
  { value: "LOTUS", label: "LOTUS" },
  { value: "MAHINDRA", label: "MAHINDRA" },
  { value: "MASERATI", label: "MASERATI" },
  { value: "MATRA", label: "MATRA" },
  { value: "MAYBACH", label: "MAYBACH" },
  { value: "MAZDA", label: "MAZDA" },
  { value: "MENON", label: "MENON" },
  { value: "MERCURY", label: "MERCURY" },
  { value: "MITSUBISHI", label: "MITSUBISHI" },
  { value: "MG", label: "MG" },
  { value: "MINI", label: "MINI" },
  { value: "MIURA", label: "MIURA" },
  { value: "MORRIS", label: "MORRIS" },
  { value: "MP LAFER", label: "MP LAFER" },
  { value: "MPLM", label: "MPLM" },
  { value: "NEWTRACK", label: "NEWTRACK" },
  { value: "NISSIN", label: "NISSIN" },
  { value: "OLDSMOBILE", label: "OLDSMOBILE" },
  { value: "PAG", label: "PAG" },
  { value: "PAGANI", label: "PAGANI" },
  { value: "PLYMOUTH", label: "PLYMOUTH" },
  { value: "PUMA", label: "PUMA" },
  { value: "RENO", label: "RENO" },
  { value: "REVA-I", label: "REVA-I" },
  { value: "ROLLS-ROYCE", label: "ROLLS-ROYCE" },
  { value: "ROMI", label: "ROMI" },
  { value: "SEAT", label: "SEAT" },
  { value: "UTILITARIOS AGRICOLAS", label: "UTILITARIOS AGRICOLAS" },
  { value: "SHINERAY", label: "SHINERAY" },
  { value: "SAAB", label: "SAAB" },
  { value: "SHORT", label: "SHORT" },
  { value: "SIMCA", label: "SIMCA" },
  { value: "SMART", label: "SMART" },
  { value: "SPYKER", label: "SMART" },
  { value: "STANDARD", label: "STANDARD" },
  { value: "STUDEBAKER", label: "STUDEBAKER" },
  { value: "TAC", label: "TAC" },
  { value: "TANGER", label: "TAC" },
  { value: "TRIUMPH", label: "TRIUMPH" },
  { value: "TROLLER", label: "TROLLER" },
  { value: "UNIMOG", label: "UNIMOG" },
  { value: "WIESMANN", label: "WIESMANN" },
  { value: "CADILLAC", label: "CADILLAC" },
  { value: "AM GEN", label: "AM GEN" },
  { value: "BUGGY", label: "BUGGY" },
  { value: "WILLYS OVERLAND", label: "WILLYS OVERLAND" },
  { value: "KASEA", label: "KASEA" },
  { value: "SATURN", label: "SATURN" },
  { value: "SWELL MINI", label: "SWELL MINI" },
  { value: "SKODA", label: "SKODA" },
  { value: "KARMANN GHIA", label: "KARMANN GHIA" },
  { value: "KART", label: "KART" },
  { value: "HANOMAG", label: "HANOMAG" },
  { value: "OUTROS", label: "OUTROS" },
  { value: "HILLMAN", label: "HILLMAN" },
  { value: "HRG", label: "HRG" },
  { value: "GAIOLA", label: "GAIOLA" },
  { value: "TATA", label: "TATA" },
  { value: "DITALLY", label: "DITALLY" },
  { value: "RELY", label: "RELY" },
  { value: "MCLAREN", label: "MCLAREN" },
  { value: "GEELY", label: "GEELY" }
]

export const listFuel = [
  { value: 'Alcool', label: 'Alcool' },
  { value: 'Alcool e GNV', label: 'Alcool e GNV' },
  { value: 'Diesel', label: 'Diesel' },
  { value: 'GNV', label: 'GNV' },
  { value: 'Gasolina', label: 'Gasolina' },
  { value: 'Flex', label: 'Flex' },
  { value: 'Hibrido', label: 'Híbrido' },
  { value: 'Eletrico', label: 'Eletrico' },
  { value: 'Gas. e GNV', label: 'Gas. e GNV' },
  { value: 'Gas./Alc./GNV', label: 'Gas./Alc./GNV' }
]

export const listColor = [
  { value: 'Indefinida', label: 'Indefinida' },
  { value: 'Amarelo', label: 'Amarelo' },
  { value: 'Azul', label: 'Azul' },
  { value: 'Bege', label: 'Bege' },
  { value: 'Branco', label: 'Branco' },
  { value: 'Bronze', label: 'Bronze' },
  { value: 'Cinza', label: 'Cinza' },
  { value: 'Dourado', label: 'Dourado' },
  { value: 'Laranja', label: 'Laranja' },
  { value: 'Marron', label: 'Marron' },
  { value: 'Prata', label: 'Prata' },
  { value: 'Preta', label: 'Preta' },
  { value: 'Rosa', label: 'Rosa' },
  { value: 'Roxo', label: 'Roxo' },
  { value: 'Verde', label: 'Verde' },
  { value: 'Vermelho', label: 'Vermelho' },
  { value: 'Vinho', label: 'Vinho' }
]

export const ufList = [
  { value: "", label: "" },
  { value: "AC", label: "AC" },
  { value: "AL", label: "AL" },
  { value: "AP", label: "AP" },
  { value: "AM", label: "AM" },
  { value: "BA", label: "BA" },
  { value: "CE", label: "CE" },
  { value: "DF", label: "DF" },
  { value: "ES", label: "ES" },
  { value: "GO", label: "GO" },
  { value: "MA", label: "MA" },
  { value: "MT", label: "MT" },
  { value: "MS", label: "MS" },
  { value: "MG", label: "MG" },
  { value: "PA", label: "PA" },
  { value: "PB", label: "PB" },
  { value: "PR", label: "PR" },
  { value: "PE", label: "PE" },
  { value: "PI", label: "PI" },
  { value: "RJ", label: "RJ" },
  { value: "RN", label: "RN" },
  { value: "RS", label: "RS" },
  { value: "RO", label: "RO" },
  { value: "RR", label: "RR" },
  { value: "SC", label: "SC" },
  { value: "SP", label: "SP" },
  { value: "SE", label: "SE" },
  { value: "TO", label: "TO" }
]

export const genderList = [
  { value: "masculino", label: "Masculino" },
  { value: "feminino", label: "Feminino" }
]

export const maritalStatusList = [
  { value: "Casado(a)", label: "Casado(a)" },
  { value: "Solteiro(a)", label: "Solteiro(a)" },
  { value: "Divorciado(a)", label: "Divorciado(a)" },
  { value: "Viúvo(a)", label: "Viúvo(a)" },
  { value: "Separado(a)", label: "Separado(a)" }
]

export const contactTypes = [
  { value: "Celular", label: "Celular" },
  { value: "Fixo", label: "Fixo" }
]

export const banksList = [
  { value: "001", label: "001 - BANCO DO BRASIL" },
  { value: "341", label: "341 - ITAÚ" },
  { value: "104", label: "104 - CAIXA ECONÔMICA FEDERAL" },
  { value: "033", label: "033 - BANCO SANTANDER S.A." },
  { value: "070", label: "070 - BRB - BANCO DE BRASÍLIA" },
  { value: "077", label: "077 - BANCO INTER" },
  { value: "237", label: "237 - BRADESCO" },
  { value: "745", label: "745 - CITIBANK" },
  { value: "422", label: "422 - BANCO SAFRA" },
  { value: "399", label: "399 - BANCO HSBC" },
  { value: "756", label: "756 - BANCOOB" },
  { value: "212", label: "212 - BANCO ORIGINAL" },
  { value: "002", label: "002 - BANCO CENTRAL DO BRASIL" },
  { value: "003", label: "003 - BANCO DA AMAZONIA S.A" },
  { value: "004", label: "004 - BANCO DO NORDESTE DO BRASIL S.A" },
  { value: "007", label: "007 - BANCO NAC DESENV. ECO. SOCIAL S.A" },
  { value: "008", label: "008 - BANCO MERIDIONAL DO BRASIL" },
  { value: "020", label: "020 - BANCO DO ESTADO DE ALAGOAS S.A" },
  { value: "021", label: "021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A" },
  { value: "022", label: "022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA" },
  { value: "024", label: "024 - BANCO DO ESTADO DE PERNAMBUCO" },
  { value: "025", label: "025 - BANCO ALFA S/A" },
  { value: "026", label: "026 - BANCO DO ESTADO DO ACRE S.A" },
  { value: "027", label: "027 - BANCO DO ESTADO DE SANTA CATARINA S.A" },
  { value: "028", label: "028 - BANCO DO ESTADO DA BAHIA S.A" },
  { value: "029", label: "029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A" },
  { value: "030", label: "030 - BANCO DO ESTADO DA PARAIBA S.A" },
  { value: "031", label: "031 - BANCO DO ESTADO DE GOIAS S.A" },
  { value: "032", label: "032 - BANCO DO ESTADO DO MATO GROSSO S.A." },
  { value: "034", label: "034 - BANCO DO ESADO DO AMAZONAS S.A" },
  { value: "035", label: "035 - BANCO DO ESTADO DO CEARA S.A" },
  { value: "036", label: "036 - BANCO DO ESTADO DO MARANHAO S.A" },
  { value: "037", label: "037 - BANCO DO ESTADO DO PARA S.A" },
  { value: "038", label: "038 - BANCO DO ESTADO DO PARANA S.A" },
  { value: "039", label: "039 - BANCO DO ESTADO DO PIAUI S.A" },
  { value: "041", label: "041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A" },
  { value: "047", label: "047 - BANCO DO ESTADO DE SERGIPE S.A" },
  { value: "048", label: "048 - BANCO DO ESTADO DE MINAS GERAIS S.A" },
  { value: "059", label: "059 - BANCO DO ESTADO DE RONDONIA S.A" },
  { value: "106", label: "106 - BANCO ITABANCO S.A." },
  { value: "107", label: "107 - BANCO BBM S.A" },
  { value: "109", label: "109 - BANCO CREDIBANCO S.A" },
  { value: "116", label: "116 - BANCO B.N.L DO BRASIL S.A" },
  { value: "148", label: "148 - MULTI BANCO S.A" },
  { value: "151", label: "151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO" },
  { value: "153", label: "153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL" },
  { value: "165", label: "165 - BANCO NORCHEM S.A" },
  { value: "166", label: "166 - BANCO INTER-ATLANTICO S.A" },
  { value: "168", label: "168 - BANCO C.C.F. BRASIL S.A" },
  { value: "175", label: "175 - CONTINENTAL BANCO S.A" },
  { value: "184", label: "184 - BBA - CREDITANSTALT S.A" },
  { value: "199", label: "199 - BANCO FINANCIAL PORTUGUES" },
  { value: "200", label: "200 - BANCO FRICRISA AXELRUD S.A" },
  { value: "201", label: "201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A" },
  { value: "204", label: "204 - BANCO S.R.L S.A" },
  { value: "205", label: "205 - BANCO SUL AMERICA S.A" },
  { value: "206", label: "206 - BANCO MARTINELLI S.A" },
  { value: "208", label: "208 - BANCO PACTUAL S.A" },
  { value: "210", label: "210 - DEUTSCH SUDAMERIKANICHE BANK AG" },
  { value: "211", label: "211 - BANCO SISTEMA S.A" },
  { value: "213", label: "213 - BANCO ARBI S.A" },
  { value: "214", label: "214 - BANCO DIBENS S.A" },
  { value: "215", label: "215 - BANCO AMERICA DO SUL S.A" },
  { value: "216", label: "216 - BANCO REGIONAL MALCON S.A" },
  { value: "217", label: "217 - BANCO AGROINVEST S.A" },
  { value: "218", label: "218 - BS2" },
  { value: "219", label: "219 - BANCO DE CREDITO DE SAO PAULO S.A" },
  { value: "220", label: "220 - BANCO CREFISUL" },
  { value: "221", label: "221 - BANCO GRAPHUS S.A" },
  { value: "222", label: "222 - BANCO AGF BRASIL S. A." },
  { value: "223", label: "223 - BANCO INTERUNION S.A" },
  { value: "224", label: "224 - BANCO FIBRA S.A" },
  { value: "225", label: "225 - BANCO BRASCAN S.A" },
  { value: "228", label: "228 - BANCO ICATU S.A" },
  { value: "229", label: "229 - BANCO CRUZEIRO S.A" },
  { value: "230", label: "230 - BANCO BANDEIRANTES S.A" },
  { value: "231", label: "231 - BANCO BOAVISTA S.A" },
  { value: "232", label: "232 - BANCO INTERPART S.A" },
  { value: "233", label: "233 - BANCO MAPPIN S.A" },
  { value: "234", label: "234 - BANCO LAVRA S.A." },
  { value: "235", label: "235 - BANCO LIBERAL S.A" },
  { value: "236", label: "236 - BANCO CAMBIAL S.A" },
  { value: "239", label: "239 - BANCO BANCRED S.A" },
  { value: "240", label: "240 - BANCO DE CREDITO REAL DE MINAS GERAIS S." },
  { value: "241", label: "241 - BANCO CLASSICO S.A" },
  { value: "242", label: "242 - BANCO EUROINVEST S.A" },
  { value: "243", label: "243 - BANCO MÁXIMA S.A" },
  { value: "244", label: "244 - BANCO CIDADE S.A" },
  { value: "245", label: "245 - BANCO EMPRESARIAL S.A" },
  { value: "246", label: "246 - BANCO ABC ROMA S.A" },
  { value: "247", label: "247 - BANCO OMEGA S.A" },
  { value: "249", label: "249 - BANCO INVESTCRED S.A" },
  { value: "250", label: "250 - BANCO SCHAHIN CURY S.A" },
  { value: "251", label: "251 - BANCO SAO JORGE S.A." },
  { value: "252", label: "252 - BANCO FININVEST S.A" },
  { value: "254", label: "254 - BANCO PARANA BANCO S.A" },
  { value: "255", label: "255 - MILBANCO S.A." },
  { value: "256", label: "256 - BANCO GULVINVEST S.A" },
  { value: "258", label: "258 - BANCO INDUSCRED S.A" },
  { value: "261", label: "261 - BANCO VARIG S.A" },
  { value: "262", label: "262 - BANCO BOREAL S.A" },
  { value: "263", label: "263 - BANCO CACIQUE" },
  { value: "264", label: "264 - BANCO PERFORMANCE S.A" },
  { value: "265", label: "265 - BANCO FATOR S.A" },
  { value: "266", label: "266 - BANCO CEDULA S.A" },
  { value: "267", label: "267 - BANCO BBM-COM.C.IMOB.CFI S.A." },
  { value: "275", label: "275 - BANCO REAL S.A" },
  { value: "277", label: "277 - BANCO PLANIBANC S.A" },
  { value: "282", label: "282 - BANCO BRASILEIRO COMERCIAL" },
  { value: "291", label: "291 - BANCO DE CREDITO NACIONAL S.A" },
  { value: "294", label: "294 - BCR - BANCO DE CREDITO REAL S.A" },
  { value: "295", label: "295 - BANCO CREDIPLAN S.A" },
  { value: "300", label: "300 - BANCO DE LA NACION ARGENTINA S.A" },
  { value: "302", label: "302 - BANCO DO PROGRESSO S.A" },
  { value: "303", label: "303 - BANCO HNF S.A." },
  { value: "304", label: "304 - BANCO PONTUAL S.A" },
  { value: "308", label: "308 - BANCO COMERCIAL BANCESA S.A." },
  { value: "318", label: "318 - BANCO B.M.G. S.A" },
  { value: "320", label: "320 - BANCO INDUSTRIAL E COMERCIAL" },
  { value: "346", label: "346 - BANCO FRANCES E BRASILEIRO S.A" },
  { value: "347", label: "347 - BANCO SUDAMERIS BRASIL S.A" },
  { value: "351", label: "351 - BANCO BOZANO SIMONSEN S.A" },
  { value: "353", label: "353 - BANCO GERAL DO COMERCIO S.A" },
  { value: "356", label: "356 - ABN AMRO S.A" },
  { value: "366", label: "366 - BANCO SOGERAL S.A" },
  { value: "369", label: "369 - PONTUAL" },
  { value: "370", label: "370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA" },
  { value: "372", label: "372 - BANCO ITAMARATI S.A" },
  { value: "375", label: "375 - BANCO FENICIA S.A" },
  { value: "376", label: "376 - CHASE MANHATTAN BANK S.A" },
  { value: "388", label: "388 - BANCO MERCANTIL DE DESCONTOS S/A" },
  { value: "389", label: "389 - BANCO MERCANTIL DO BRASIL S.A" },
  { value: "392", label: "392 - BANCO MERCANTIL DE SAO PAULO S.A" },
  { value: "394", label: "394 - BANCO B.M.C. S.A" },
  { value: "409", label: "409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS" },
  { value: "412", label: "412 - BANCO NACIONAL DA BAHIA S.A" },
  { value: "415", label: "415 - BANCO NACIONAL S.A" },
  { value: "420", label: "420 - BANCO NACIONAL DO NORTE S.A" },
  { value: "424", label: "424 - BANCO NOROESTE S.A" },
  { value: "434", label: "434 - BANCO FORTALEZA S.A" },
  { value: "453", label: "453 - BANCO RURAL S.A" },
  { value: "456", label: "456 - BANCO TOKIO S.A" },
  { value: "464", label: "464 - BANCO SUMITOMO BRASILEIRO S.A" },
  { value: "466", label: "466 - BANCO MITSUBISHI BRASILEIRO S.A" },
  { value: "472", label: "472 - LLOYDS BANK PLC" },
  { value: "473", label: "473 - BANCO FINANCIAL PORTUGUES S.A" },
  { value: "477", label: "477 - CITIBANK N.A" },
  { value: "479", label: "479 - BANCO DE BOSTON S.A" },
  { value: "480", label: "480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A" },
  { value: "483", label: "483 - BANCO AGRIMISA S.A." },
  { value: "487", label: "487 - DEUTSCHE BANK S.A - BANCO ALEMAO" },
  { value: "488", label: "488 - BANCO J. P. MORGAN S.A" },
  { value: "489", label: "489 - BANESTO BANCO URUGAUAY S.A" },
  { value: "492", label: "492 - INTERNATIONALE NEDERLANDEN BANK N.V." },
  { value: "493", label: "493 - BANCO UNION S.A.C.A" },
  { value: "494", label: "494 - BANCO LA REP. ORIENTAL DEL URUGUAY" },
  { value: "495", label: "495 - BANCO LA PROVINCIA DE BUENOS AIRES" },
  { value: "496", label: "496 - BANCO EXTERIOR DE ESPANA S.A" },
  { value: "498", label: "498 - CENTRO HISPANO BANCO" },
  { value: "499", label: "499 - BANCO IOCHPE S.A" },
  { value: "501", label: "501 - BANCO BRASILEIRO IRAQUIANO S.A." },
  { value: "502", label: "502 - BANCO SANTANDER DE NEGOCIOS S.A" },
  { value: "504", label: "504 - BANCO MULTIPLIC S.A" },
  { value: "505", label: "505 - BANCO GARANTIA S.A" },
  { value: "600", label: "600 - BANCO LUSO BRASILEIRO S.A" },
  { value: "601", label: "601 - BFC BANCO S.A." },
  { value: "602", label: "602 - BANCO PATENTE S.A" },
  { value: "604", label: "604 - BANCO INDUSTRIAL DO BRASIL S.A" },
  { value: "607", label: "607 - BANCO SANTOS NEVES S.A" },
  { value: "608", label: "608 - BANCO OPEN S.A" },
  { value: "610", label: "610 - BANCO V.R. S.A" },
  { value: "611", label: "611 - BANCO PAULISTA S.A" },
  { value: "612", label: "612 - BANCO GUANABARA S.A" },
  { value: "613", label: "613 - BANCO PECUNIA S.A" },
  { value: "616", label: "616 - BANCO INTERPACIFICO S.A" },
  { value: "617", label: "617 - BANCO INVESTOR S.A." },
  { value: "618", label: "618 - BANCO TENDENCIA S.A" },
  { value: "621", label: "621 - BANCO APLICAP S.A." },
  { value: "622", label: "622 - BANCO DRACMA S.A" },
  { value: "623", label: "623 - BANCO PANAMERICANO S.A" },
  { value: "624", label: "624 - BANCO GENERAL MOTORS S.A" },
  { value: "625", label: "625 - BANCO ARAUCARIA S.A" },
  { value: "626", label: "626 - BANCO FICSA S.A" },
  { value: "627", label: "627 - BANCO DESTAK S.A" },
  { value: "628", label: "628 - BANCO CRITERIUM S.A" },
  { value: "629", label: "629 - BANCORP BANCO COML. E. DE INVESTMENTO" },
  { value: "630", label: "630 - BANCO INTERCAP S.A" },
  { value: "633", label: "633 - BANCO REDIMENTO S.A" },
  { value: "634", label: "634 - BANCO TRIANGULO S.A" },
  { value: "635", label: "635 - BANCO DO ESTADO DO AMAPA S.A" },
  { value: "637", label: "637 - BANCO SOFISA S.A" },
  { value: "638", label: "638 - BANCO PROSPER S.A" },
  { value: "639", label: "639 - BIG S.A. - BANCO IRMAOS GUIMARAES" },
  { value: "640", label: "640 - BANCO DE CREDITO METROPOLITANO S.A" },
  { value: "641", label: "641 - BANCO EXCEL ECONOMICO S/A" },
  { value: "643", label: "643 - BANCO SEGMENTO S.A" },
  { value: "645", label: "645 - BANCO DO ESTADO DE RORAIMA S.A" },
  { value: "647", label: "647 - BANCO MARKA S.A" },
  { value: "648", label: "648 - BANCO ATLANTIS S.A" },
  { value: "649", label: "649 - BANCO DIMENSAO S.A" },
  { value: "650", label: "650 - BANCO PEBB S.A" },
  { value: "652", label: "652 - BANCO FRANCES E BRASILEIRO SA" },
  { value: "653", label: "653 - BANCO INDUSVAL S.A" },
  { value: "654", label: "654 - BANCO A. J. RENNER S.A" },
  { value: "655", label: "655 - BANCO VOTORANTIM S.A." },
  { value: "656", label: "656 - BANCO MATRIX S.A" },
  { value: "657", label: "657 - BANCO TECNICORP S.A" },
  { value: "658", label: "658 - BANCO PORTO REAL S.A" },
  { value: "702", label: "702 - BANCO SANTOS S.A" },
  { value: "705", label: "705 - BANCO INVESTCORP S.A." },
  { value: "707", label: "707 - BANCO DAYCOVAL S.A" },
  { value: "711", label: "711 - BANCO VETOR S.A." },
  { value: "713", label: "713 - BANCO CINDAM S.A" },
  { value: "715", label: "715 - BANCO VEGA S.A" },
  { value: "718", label: "718 - BANCO OPERADOR S.A" },
  { value: "719", label: "719 - BANCO PRIMUS S.A" },
  { value: "720", label: "720 - BANCO MAXINVEST S.A" },
  { value: "721", label: "721 - BANCO CREDIBEL S.A" },
  { value: "722", label: "722 - BANCO INTERIOR DE SAO PAULO S.A" },
  { value: "724", label: "724 - BANCO PORTO SEGURO S.A" },
  { value: "725", label: "725 - BANCO FINABANCO S.A" },
  { value: "726", label: "726 - BANCO UNIVERSAL S.A" },
  { value: "728", label: "728 - BANCO FITAL S.A" },
  { value: "729", label: "729 - BANCO FONTE S.A" },
  { value: "730", label: "730 - BANCO COMERCIAL PARAGUAYO S.A" },
  { value: "731", label: "731 - BANCO GNPP S.A." },
  { value: "732", label: "732 - BANCO PREMIER S.A." },
  { value: "733", label: "733 - BANCO NACOES S.A." },
  { value: "734", label: "734 - BANCO GERDAU S.A" },
  { value: "735", label: "735 - BANCO NEON" },
  { value: "736", label: "736 - BANCO UNITED S.A" },
  { value: "737", label: "737 - THECA" },
  { value: "738", label: "738 - MARADA" },
  { value: "739", label: "739 - BGN" },
  { value: "740", label: "740 - BCN BARCLAYS" },
  { value: "741", label: "741 - BRP" },
  { value: "742", label: "742 - EQUATORIAL" },
  { value: "743", label: "743 - BANCO EMBLEMA S.A" },
  { value: "744", label: "744 - THE FIRST NATIONAL BANK OF BOSTON" },
  { value: "746", label: "746 - MODAL S.A." },
  { value: "747", label: "747 - RABOBANK DO BRASIL" },
  { value: "748", label: "748 - SICREDI" },
  { value: "749", label: "749 - BRMSANTIL SA" },
  { value: "750", label: "750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA" },
  { value: "751", label: "751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A" },
  { value: "752", label: "752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S" },
  { value: "753", label: "753 - BANCO COMERCIAL URUGUAI S.A." },
  { value: "755", label: "755 - BANCO MERRILL LYNCH S.A" },
  { value: "757", label: "757 - BANCO KEB DO BRASIL S.A." },
  { value: "260", label: "260 - Nu Pagamentos S.A" },
  { value: "102", label: "102 - XP INVESTIMENTOS" },
  { value: "336", label: "336 - BANCO C6 S.A." },
  { value: "290", label: "290 - PagSeguro Internet S.A." },
  { value: "323", label: "323 - MercadoPago.com Representações Ltda." },
  { value: "332", label: "332 - Acesso Soluções de Pagamento S.A." },
  { value: "325", label: "325 - Órama DTVM S.A." },
  { value: "85", label: "85 - COOPERATIVA CENTRAL DE CREDITO - AILOS" },
  { value: "125", label: "125 - PLURAL S.A. BANCO MULTIPLO" },
  { value: "197", label: "197 - STONE PAGAMENTOS S.A." }
]

export const accountTypeList = [
  { value: "Corrente", label: "Corrente" },
  { value: "Poupança", label: "Poupança" },
  { value: "Salário", label: "Salário" }
]
